"""Config module exports"""
from .database_config import DB_CONFIG
from .storage_config import MINIO_CONFIG
from .crawler_config import (
    BASE_URL, BACKUP_DIR, NUM_PAGES, CONCURRENT_PAGES,
    PAGE_TIMEOUT, SELECTOR_TIMEOUT, MIN_DELAY, MAX_DELAY,
    DESKTOP_AGENTS, MOBILE_AGENTS, VIEWPORTS, MOBILE_VIEWPORTS,
    ANTI_DETECTION_SCRIPT, BLOCK_PATTERNS
)

__all__ = [
    'DB_CONFIG', 'MINIO_CONFIG',
    'BASE_URL', 'BACKUP_DIR', 'NUM_PAGES', 'CONCURRENT_PAGES',
    'PAGE_TIMEOUT', 'SELECTOR_TIMEOUT', 'MIN_DELAY', 'MAX_DELAY',
    'DESKTOP_AGENTS', 'MOBILE_AGENTS', 'VIEWPORTS', 'MOBILE_VIEWPORTS',
    'ANTI_DETECTION_SCRIPT', 'BLOCK_PATTERNS'
]
